### ISSUE TITLE
Support coroutines and flow?

### ISSUE THREAD

**Issue by msasikanth** [spotify/mobius#108]
Any plans to support coroutines and flow?

I have made a module with coroutines and flow support for some of the components. If this seems fine I can finish up the rest of the components and add tests before opening a PR.

https://github.com/msasikanth/mobius-ktx/tree/master/mobius-ktx

**Comment by togi** [comment]
Hello! Yes that is definitely the plan, it has however not been prioritized yet.

I did some experiments with it last fall, but it hasn't been used for any production code so far afaik: https://github.com/togi/mobius/commit/0e63bac7fadefec3d4bc15a08aeab7b0f63f6a6c

Do you have some practical experience with your variants? At first glance they do seem quite similar, especially the FlowConnectable. One thing I remember noting is that it seemed like suspending functions might be preferable to Flows in most cases (see coroutineConnectable in my commit), but I'd definitely be interested in hearing your thoughts on the topic.

**Comment by msasikanth** [comment]
One of the reasons I went with flows is that I need to listen to Room. 

I wanted to have similar behaviour as `RxMobius.SubtypeEffectHandler` in terms of how it handles data streams and easier thread switching. I am still using suspending functions to run the block of code provided for actions and consumer. 

Within those suspending function in actions and consumer, we can use `withContext` if we want to switch the dispatcher.

**Comment by msasikanth** [comment]
I remember making a coroutine based connectable and use flow there as well. But the `RxMobius` API seemed nicer. Decided to give this approach a try 🤷 . So current implementation looks this

```kotlin
FlowMobius
  .subtypeEffectHandler()
  .addAction(ShowError::class, {
      uiActions.showError()
   }, Dispatchers.Main)
  .build()
```

**Comment by togi** [comment]
My intention with coroutineConnectable was to enable writing code like this:

```kotlin
coroutineConnectable { effect, dispatchEvent -> 
    when (effect) {
        is ShowError -> withContext(Main) {
            uiActions.showError()
        }

        is WriteToDatabase -> {
            database.withTransaction {
                database.someDao().insertThing(effect.thing)
            }
            dispatchEvent(WriteToDatabaseComplete)
        }
    }
}
```

**Comment by msasikanth** [comment]
It was a bit similar but I haven't written the extension function, I wanted to be able to extend the class. But now that I see the extension function seems pretty good 🤔 . 

I didn't understand why you provided `parentScope` in `CoroutineConnectable` constructor though.

**Comment by togi** [comment]
Hmm it was some time since I wrote it, I'm not sure I remember the reason. It's quite possible it can be removed.

**Comment by msasikanth** [comment]
Found my old implementation, this what I was experimenting/using before

```kotlin
abstract class CoroutineConnectable<I, O>(
  private val dispatcher: CoroutineDispatcher = Dispatchers.Default
) : Connectable<I, O>, CoroutineScope {

  private val parentJob = SupervisorJob()
  override val coroutineContext: CoroutineContext
    get() = dispatcher

  abstract suspend fun handler(effect: I, dispatchEvent: (O) -> Unit)

  @ExperimentalCoroutinesApi
  override fun connect(output: Consumer<O>): Connection<I> {
    val job = Job()
    val scope = CoroutineScope(coroutineContext + job)

    return object : Connection<I> {
      override fun accept(input: I) {
        scope.launch { handler(input, output::accept) }
      }

      override fun dispose() {
        job.cancel()
        parentJob.cancel()
      }
    }
  }
}
```

**Comment by togi** [comment]
Nice! The fact that they are quite similar probably means something good :)

The next step I had in mind was actually to start over with CoroutineConnectable from scratch and use TDD to try to cover a bunch of concurrency and error cases. I think the result might not be very different, but we're trying to be quite diligent when it comes to concurrency and testing in Mobius.

I'm not sure when we will have time looking at it, but if you would like to try out the CoroutineConnectable (either your or my version) before that and give us feedback on how it works, or maybe even contribute to test-driving a new implementation, that would certainly be very welcome!

When it comes to Flow I think while we should support it to some extent, I'm not really convinced it's a good idea to port over the full SubtypeEffectHandler. I see that mostly as a tool for being able to express the routing in Java using RxJava, and I think the CoroutineConnectable is able to express the same thing in a much more flexible and kotlin-idiomatic way.

**Comment by msasikanth** [comment]
I have gone back to using my old CoroutineConnectable in one of my recent side projects. When writing tests I had to use `runBlocking`.  Other than that, it was pretty easy implementation, if I make any more changes or have issues with this implementation I will let you folks know 👍

**Comment by jaimegc** [comment]
Hi guys! Any update on this topic? I'd be amazing to have coroutines & flow

**Comment by codeCleanDev** [comment]
hey any news on this

**Comment by togi** [comment]
Not yet, we're in the process of evaluating coroutines for internal use but we're still primarily using RxJava and haven't worked more on this yet. Contributions are still welcome!

**Comment by renatanunes-spotify** [comment]
Since there's now an amazing library called [Flowbius](https://github.com/atlassian-labs/Flowbius) created by our friends at Trello, I will close this issue if that's okay. :)

Feel free to reply/create another one if you have more questions!
