### ISSUE TITLE
Mobius with Android lifcycle 

### ISSUE THREAD

**Issue by codeCleanDev** [spotify/mobius#138]
Hello All.. I have Presenter with two lifcycle OnAttachToView and onDetachFromView which will called for Fragment Lifecycle OnStart and OnStop. The question is "Do i really need the on Pause and On Resume Events for starting and stopping the loop?"

**Comment by togi** [comment]
Mobius itself is agnostic of Android, and you can really give it any lifetime you want. For example, you can run a loop in the Application class, in a Service, or in a ViewModel.

There are some potential gotchas with Android lifecycles, like for example Activity.onDestroy isn't guaranteed to be called, and onSaveInstanceState will called before onStop (see #42 for a more detailed explanation), but if you would prefer to use onStart/onStop instead of onResume/onPause, that can certainly be done as long as you keep in mind that there might be some issues like that.

**Comment by codeCleanDev** [comment]
So what if i want to use the ViewModel in AC?

**Comment by codeCleanDev** [comment]
I use this library for the Presenter (
https://github.com/grandcentrix/ThirtyInch )  and it has only OnStart and
OnStop lifcycle..

**Comment by togi** [comment]
I'm not familiar with that particular library, but from a quick look it looks like it doesn't support state restore at all. For most applications you probably do want to implement state restore, but if you're fine with not having that then you should be able to use onStart and onStop without any issue.

**Comment by codeCleanDev** [comment]
No it's dose support state restore and retaining instances

**Comment by togi** [comment]
Alright, as I said I'm not familiar with that library and that was just my first impression, I could only find code that retains the presenter. Using `onAttachToView` and `onDetachFromView` would probably be the most similar to our mobius samples that use `onResume` and `onPause`, but `onStart` and `onStop` should work too (with the caveat that if there is indeed a state save mechanism then you might call `getMostRecentModel()` before the loop is stopped, causing any state changes after that to not be saved).

Did you run into any issues when trying to use mobius together with thirtyinches?

**Comment by codeCleanDev** [comment]
So this is what i came up with { makes the loop lives as long as my
Presenter(without using a controller) alive and then observing the most
recent model and and the view effects like the MobiusloopViewModel

**Comment by togi** [comment]
I don't think we'll add any official support for thirtyinches, but if you want something similar to MobiusLoopViewModel, you should be able to copy its implementation and adopt it for TiPresenter.

**Comment by codeCleanDev** [comment]
So with this approach is it safe to use Context on my effects handling

**Comment by togi** [comment]
As long as you are using Application context you should be safe. You should make sure to always use Application context in TiPresenter either way, since it can outlive the hosting activity.

**Comment by codeCleanDev** [comment]
Thanks
