### ISSUE TITLE
Migrate wiki to GitHub Pages + MkDocs ❤️

### ISSUE THREAD

**Issue by vestrel00** [spotify/mobius#153]
Hi! I've been using this **awesome** library for over two years now for work (and sometimes for personal use). One of my former colleagues even went through all of the trouble and red-tape of open sourcing [Flowbius](https://github.com/atlassian-labs/Flowbius) 🤯

We've been using the [wiki](https://github.com/spotify/mobius/wiki) as our main point of reference when working with Mobius and for when we onboard folks into the team. It's great. I have no complaints. The wiki is very well organized and does the job just fine. However, I think we can improve on it 😁

## Why migrate the wiki to GitHub Pages + [MkDocs](https://www.mkdocs.org)?

Why "fix" something that is not broken? This is one of the all-time most frequently asked questions in software development (IMO). As I mentioned, the wiki is fine. I am not saying the wiki "needs to be fixed". So then why?

[MkDocs](https://www.mkdocs.org), in particular the [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/)...

- is used by a lot of companies and successful OSS.
    - [Atlassian](https://atlassian.github.io/data-center-helm-charts/), [AWS](https://aws.github.io/copilot-cli/), [Binance](https://docs.binance.org/), [Bloomberg](https://bloomberg.github.io/selekt/), [CERN](http://abpcomputing.web.cern.ch/), [Datadog](https://datadoghq.dev/integrations-core/), [Google](https://google.github.io/accompanist/), [ING](https://ing-bank.github.io/baker/), [Intel](https://open-amt-cloud-toolkit.github.io/docs/), [LinkedIn](https://linkedin.github.io/school-of-sre/), [Microsoft](https://microsoft.github.io/code-with-engineering-playbook/), [Mozilla](https://mozillafoundation.github.io/engineering-handbook/), [Netflix](https://netflix.github.io/titus/), [Salesforce](https://policy-sentry.readthedocs.io/en/latest/), [SoundCloud](https://intervene.dev/), [Square](https://square.github.io/okhttp/), [Zalando](https://opensource.zalando.com/skipper/)
    - [Google's Accompanist](https://google.github.io/accompanist/), [Arduino](https://arduino.github.io/arduino-cli/), [AutoKeras](https://autokeras.com/), [BFE](https://www.bfe-networks.net/), [CentOS](https://docs.infra.centos.org/), [Crystal](https://crystal-lang.org/reference/), [Electron](https://www.electron.build/), [FastAPI](https://fastapi.tiangolo.com/), [Knative](https://knative.dev/docs/), [Kubernetes](https://kops.sigs.k8s.io/), [kSQL](https://docs.ksqldb.io/), [Nokogiri](https://nokogiri.org/), [OpenFaaS](https://docs.openfaas.com/), [Pi-Hole](https://docs.pi-hole.net/), [Pydantic](https://pydantic-docs.helpmanual.io/), [Renovate](https://docs.renovatebot.com/), [Traefik](https://docs.traefik.io/), [Vapor](https://docs.vapor.codes/), [ZeroNet](https://zeronet.io/docs/), [WTF](https://wtfutil.com/)
    - I'm sure Spotify is probably using it for some of the newer FOSS projects.
-  is **searchable**
- looks and feels better than the wiki in desktop and mobile (IMO)
- you get a free website out of it

I will not talk about the pros and cons of GitHub wiki vs GitHub Pages. It's up to you to do that research if you care. It's mostly just preference and opinions, IMO anyways 🤭

## You get this work for free

I think that you are all aware of MkDocs and have probably considered or are considering using it. Maybe ya'll just don't have the time to do it or just can't be bothered to fix something that ain't broke. Or maybe you even prefer the wiki and are consciously making the decision to use it instead of GitHub Pages + MkDocs. 

Either way, I've already done the work for you 🤗. It's been a pleasure to be able to have the opportunity to do this work for one of my all-time favorite FOSS projects. I had fun doing it. As a bonus, I learned even more about Mobius in the process. Regardless of whether you merge my PR or not, thanks for everything 🍻

If you do decide to migrate, you can just merge my PR (or just use it as reference). More info including demo videos and next steps are in the PR. 

https://github.com/spotify/mobius/pull/154

Here is what it looks like in my fork; https://vestrel00.github.io/mobius/

**Comment by renatanunes-spotify** [comment]
Hey @vestrel00, amazing work you did here, truly appreciated! 
I've already checked and it looks much better than the old wiki 🙂
We'll finish your PR review and merge it soon 🙏🏼

**Comment by vestrel00** [comment]
WOW 🤯 Thanks @renatanunes-spotify ! I'm super stoked to have been able to contribute a tiny bit to this piece of art! 

❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️
