### ISSUE TITLE
sample project 

### ISSUE THREAD

**Issue by shakil807g** [spotify/mobius#16]
add a sample project with kotlin

**Comment by togi** [comment]
Absolutely! We haven't had time to publish one yet but there will definitely be sample projects for both Java and Kotlin. Anything in particular you'd like to see in the sample project?

**Comment by shakil807g** [comment]
i would be great if sample project in both java and kotlin can exhibit the real use cases in app and show as much as possible the complete power of this framework

**Comment by bangarharshit** [comment]
It will be great if you can demo a basic project with all the core concepts like external events (maybe android location), normal events, and side effects. Without a demo project, it is really hard to understand and use the library.

**Comment by pettermahlen** [comment]
@bangarharshit it would be great to hear a little more about which areas are particularly difficult to understand, so that we could perhaps also try to find ways of improving the documentation. A sample app is coming up, but there may be other things we could also do with the docs.

**Comment by bangarharshit** [comment]
The wikis are very clear. It is just that it is hard to think of how to write an app with it.

**Comment by alissonfpmorais** [comment]
I've made a toy project to test mobius, maybe you can find useful. It's totally written in Kotlin and uses RxJava. Here's the link for my [demo](https://github.com/alissonfpmorais/AudioTest).
Let me know if it help and/or any feedback that you might have.

Another point to we discuss is that, maybe we can create some more complex samples to improve docs and help others. One way is writing our version of [Google's android architecture components](https://github.com/googlesamples/android-architecture-components). What you guys think?

**Comment by alissonfpmorais** [comment]
@pettermahlen i'm glad to hear, thanks! The feedback as issues is better to keep a track and improve the demo. I'll start another app for college (about finances management) and have plans to blog about it, so any feedback is highly appreciated.

I'm also happy to know about this TODO app, excited to see it. If any help is wanted, just let me know.

**Comment by sgrekov** [comment]
Hi! I also made a sample of using Mobius in Android project 
https://github.com/sgrekov/AndroidMobiusSample

Would be happy for any feedback!

**Comment by togi** [comment]
@sgrekov very nice! we'll open issues on your repository with feedback like we did with alisson, if that's okay with you.

**Comment by sgrekov** [comment]
@togi That would be very nice!

**Comment by Ghedeon** [comment]
@pettermahlen I think the TODO app from Android Architecture Blueprints you've mentioned would be just the perfect start. There is already this MVI interpretation of said app https://github.com/oldergod/android-architecture, and having Mobius version will make it a perfect showcase. Kind of Lenna for image processing)

**Comment by anawara** [comment]
Hey everyone, I just published the [sample app](https://github.com/spotify/mobius-android-sample) based on the TODO app from architecture blueprints. Let me know if you have any questions!

**Comment by pettermahlen** [comment]
Closing this as there are now multiple samples.
