### ISSUE TITLE
iOS Port?

### ISSUE THREAD

**Issue by PedroAlvarado** [spotify/mobius#18]
Great work and thank you for releasing this library. Is there an iOS counterpart for mobius in the works?

**Comment by pettermahlen** [comment]
There is, for Swift, but we have nothing concrete to share about timelines just yet. If there is interest in trying it out, we could perhaps consider open-sourcing that before we're "done" with proving it internally.

**Comment by PedroAlvarado** [comment]
Its great to hear that a swift-based version of mobius may be a possibility. Having a consistent cross-platform architecture experience can make life easier for native apps. This will enable Mobius to be in similar grounds with https://github.com/uber/RIBs. It'd be great to see a preliminary/alpha version when ready. Exciting!

**Comment by drd** [comment]
Definitely interested in a Swift version, because then I won't be tempted to write one :)

**Comment by bootstraponline** [comment]
I think it'd be awesome to see the Swift version, even before it's ready. 🙂

**Comment by RodrigoLGuimaraes** [comment]
Just came to know mobius and it pretty much aligns with what I'm trying to do here, would love to have a Swift port, even if incomplete, to at least dive deeper into some concepts that are much easier understood by looking at code. :)

**Comment by bootstraponline** [comment]
@pettermahlen Is there an update on the Swift port for mobius? I think it'd be valuable even if it's not done yet.

**Comment by pettermahlen** [comment]
The current status is that we're in the process of rolling out the first couple of uses into production code. We know we have some things we want to change in the APIs, and as usual there are more things to do than people to do them. The idea was to make those changes before releasing, but we'll consider releasing a preview version as open source, it's mostly a prioritisation issue at the moment.

**Comment by jeppes** [comment]
Good news! The Swift version is now open source: https://github.com/spotify/mobius.swift 🎉

**Comment by pettermahlen** [comment]
Closing this issue after a year and a day. Hopefully that'll be the slowest fix we'll ever make in this repo... :)
