### ISSUE TITLE
Any plans on integrating LifecycleObserver/Lifecycle-Aware Components?

### ISSUE THREAD

**Issue by almeric** [spotify/mobius#20]
Are there any plans on integrating the 'new' Architecture components into this library? 

I can imagine using LifecycleObserver in the controller could simplify calling all those lifecycle methods  mentioned in the [wiki](https://github.com/spotify/mobius/wiki/Mobius-and-Android#connecting-the-mobiusloopcontroller-to-a-fragment)

**Comment by pettermahlen** [comment]
We have no concrete plans, but we have been talking about this as a useful layer on top of Mobius. It's not likely that we'll get to doing that soon, but I'd say it is an area where we'd welcome contributions.

**Comment by almeric** [comment]
Thanks!

Maybe I'll take a stab at it when taking Mobius for a spin. 
Closing for now.
