### ISSUE TITLE
Infinite Scrolling with Mobius

### ISSUE THREAD

**Issue by PedroAlvarado** [spotify/mobius#29]
What would be the recommended approach to tackle RecylerView infinite scrolling with Mobius? I'm wondering if you guys have any experience/tips to share on the subject.

**Comment by pettermahlen** [comment]
What in particular is it you're asking? I can think of a couple of problems related to 'infinite' scrolling: 

1. Performance when scrolling with very large amounts of data.
1. Performance when single data items change in a very large list of data.
1. Handling look-ahead/fetching the next set of data items in a truly infinite list.

Could you describe a bit more about your use case?

**Comment by PedroAlvarado** [comment]
I didn't know I had left this open. Anyhow, It'd be great to know of your experience with regards 1 and 2 as it pertains to mobius. One way to think about this is to manage the "page" and "items"(max-size, loaded count, etc) state via the model while propagating "next page" events and effects to read and propagate new data.
