### ISSUE TITLE
Proguard Rules missing

### ISSUE THREAD

**Issue by BharathMG** [spotify/mobius#37]
Hi!

Thanks for this wonderful library. Can you guys help with proguard rules for the dependencies in this library?

**Comment by anawara** [comment]
@BharathMG glad you're enjoying it. I'm not sure what you need help with. We don't have any particular proguard requirements as far as I remember. Is there something in particular that isn't working for you?

**Comment by BharathMG** [comment]
Hi @anawara,

When building release apks with mobius libraries, we got proguard errors with **slf4j**. I added -dontwarn rules for slf4j which resolved it. So I then noticed that mobius libraries don't have **consumerProguardRules** which will be helpful for applications using it. Following rules works for me,

```
-dontwarn org.slf4j.**
-dontwarn com.spotify.mobius.**
```

I will close this issue as this is not blocking my work anymore.
