### ISSUE TITLE
Consumer is not called when effect is dispatched in Init

### ISSUE THREAD

**Issue by nominalista** [spotify/mobius#55]
I've encountered some issues with dispatching effects from Init function. 

Let's say that Init looks like this:
```kotlin
override fun init(model: MyModel): First<MyModel, MyEffect> {
    return first(model,  effects(SomeEffect))
}
```

and we add Consumer like this:
```kotlin
RxMobius.subtypeEffectHandler<MyEffect, MyEvent>()
    .addConsumer(SomeEffect::class.java, { doSomething() }, mainThread())
    .build()
```

Now the problem is that ```doSomething()``` is never called. Interestingly when I use ```io()``` scheduler everything works fine. Can someone give a clue what's the reason?

**Comment by pettermahlen** [comment]
Could you share some more details about the setup? That the effect handler doesn't get executed when you're trying to run it on the main thread indicates something like a deadlock or so to me, but not really sure. How do you set up the loop itself with regard to event and effect runners?

**Comment by nominalista** [comment]
I found the cause of the problem, it is related to loop start/stop. Start was calling twice and effect handler didn't have enough time to catch it before second start was invoked? (weird, I don't understand why it behaved it this way). The conclusion is that after fixing loop launch, everything works fine. The issue was my fault and I think it can be closed.

**Comment by pettermahlen** [comment]
OK, thanks for letting us know!
