### ISSUE TITLE
Gradle sync issue in Android Studio 3.3.2

### ISSUE THREAD

**Issue by ragunathjawahar** [spotify/mobius#59]
When I try to sync the downloaded Mobius project, my sync fails with the following error message.
```
ERROR: No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android
```

**Installed version of Android Studio**
```
Android Studio 3.3.2
Build #AI-182.5107.16.33.5314842, built on February 16, 2019
JRE: 1.8.0_152-release-1248-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6
```

I was able to fix this problem by changing the android build tools Gradle plugin version from `3.0.1` to `3.1.0`.

Can send a PR if required.

**Comment by pettermahlen** [comment]
Thanks for the report, a PR would be very welcome!
